# Generated by Django 2.2.5 on 2020-04-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('office', models.CharField(default='', max_length=30)),
                ('about', models.TextField(default='', max_length=500)),
                ('picture', models.ImageField(blank=True, upload_to='static/pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=35)),
                ('howto', models.TextField(default='', max_length=500)),
                ('video', models.ImageField(blank=True, upload_to='static/videos')),
            ],
        ),
    ]
