# Generated by Django 2.2.5 on 2020-05-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20200508_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='loan_status',
            field=models.CharField(max_length=10),
        ),
    ]
