# Generated by Django 2.2.5 on 2020-05-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20200508_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='loan_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
