# Generated by Django 2.2.5 on 2020-05-12 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20200508_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
