# Generated by Django 2.2.5 on 2020-05-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20200512_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='phn',
            field=models.TextField(default='', max_length=11),
        ),
    ]
