# Generated by Django 2.2.5 on 2020-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_contributor_phn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='phn',
            field=models.CharField(default='', max_length=11),
        ),
    ]
