# Generated by Django 2.2.5 on 2020-05-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_auto_20200512_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='video',
        ),
    ]
