# Generated by Django 2.2.5 on 2020-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_prediction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='loan_status',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
