# Generated by Django 2.2.5 on 2020-05-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_auto_20200516_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='video_type',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
