# Generated by Django 2.2.5 on 2020-06-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_auto_20200516_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='video_type',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
