# Generated by Django 2.2.5 on 2020-10-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_auto_20200831_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='loan_amount',
            field=models.FloatField(),
        ),
    ]
