# Generated by Django 2.2.5 on 2020-10-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
