# Generated by Django 2.2.5 on 2020-10-16 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('lat', models.FloatField(max_length=35)),
                ('lng', models.FloatField(max_length=35)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ('city',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('degree_of_perfection', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_of_perfection', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=35)),
                ('title', models.CharField(max_length=35)),
                ('description', models.TextField(max_length=35)),
                ('image1', models.ImageField(upload_to='static/portfolio/images')),
                ('image2', models.ImageField(upload_to='static/portfolio/images')),
                ('image3', models.ImageField(upload_to='static/portfolio/images')),
                ('proj_url', models.URLField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.ProductCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(blank=True, max_length=8, null=True)),
                ('lga', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=11)),
                ('mrt', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='static/blog/profile_pictures')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='static/blog/cover_pictures')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('business', models.TextField(blank=True, null=True)),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('instagram_page', models.URLField(blank=True, null=True)),
                ('twitter_page', models.URLField(blank=True, null=True)),
                ('pinrest_page', models.URLField(blank=True, null=True)),
                ('works_completed', models.IntegerField(blank=True, null=True)),
                ('yrs_exp', models.IntegerField(blank=True, null=True)),
                ('total_clients', models.IntegerField(blank=True, null=True)),
                ('awards', models.IntegerField(blank=True, null=True)),
                ('bus_profile', models.ImageField(blank=True, null=True, upload_to='static/Services/profile')),
                ('bus_logo', models.ImageField(blank=True, null=True, upload_to='static/Services/logo')),
                ('bus_title', models.CharField(default='', max_length=35)),
                ('persuade', models.TextField(default='', max_length=150)),
                ('bus_decription', models.TextField(default='', max_length=300)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.Cities')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
