# Generated by Django 2.2.5 on 2020-10-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20201018_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='business',
            field=models.TextField(default='', max_length=25),
        ),
    ]
