# Generated by Django 2.2.5 on 2020-10-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20201018_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='pinrest_page',
            new_name='linkedin_page',
        ),
        migrations.AddField(
            model_name='biodata',
            name='skype_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
