# Generated by Django 2.2.5 on 2020-10-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20201018_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='linkedin_page',
            new_name='linked_in',
        ),
    ]
