# Generated by Django 2.2.5 on 2020-10-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20201019_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='highest_qualification',
            field=models.CharField(default='', max_length=25),
        ),
    ]
