# Generated by Django 2.2.5 on 2020-10-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20201019_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='awards',
            new_name='annual_working_hours',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='biodata',
            name='number_of_workers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/skills/images'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='degree_of_perfection',
            field=models.IntegerField(),
        ),
    ]
