# Generated by Django 2.2.5 on 2020-10-19 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0010_auto_20201019_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=35)),
                ('logo', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biodata',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='interests', to='personal.Interest'),
        ),
    ]
