# Generated by Django 2.2.5 on 2020-10-19 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_auto_20201019_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='proj_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='degree_of_perfection',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
