# Generated by Django 2.2.5 on 2020-10-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_auto_20201019_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='annual_working_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='number_of_workers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='total_clients',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='works_completed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
