# Generated by Django 2.2.5 on 2020-10-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_auto_20201019_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='color',
            field=models.CharField(default=True, max_length=35),
        ),
    ]
