# Generated by Django 2.2.5 on 2020-10-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_interest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(default='', max_length=35),
        ),
    ]
