# Generated by Django 2.2.5 on 2020-10-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_auto_20201019_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='interest',
            field=models.ManyToManyField(to='personal.Interest'),
        ),
    ]
