# Generated by Django 2.2.5 on 2020-10-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='business',
            field=models.CharField(default='', max_length=25),
        ),
    ]
