# Generated by Django 2.2.5 on 2020-10-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_auto_20201020_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='degree_of_perfection',
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='services',
            name='logo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
