# Generated by Django 2.2.5 on 2020-10-21 07:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0021_auto_20201020_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('year_started', models.PositiveIntegerField(default=1960, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2020)])),
                ('year_completed', models.PositiveIntegerField(default=1960, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2020)])),
                ('address', models.TextField(default='', max_length=100)),
                ('experience', models.CharField(blank=True, max_length=300)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_qualification', models.CharField(max_length=50)),
                ('year_started', models.PositiveIntegerField(default=1960, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2020)])),
                ('year_completed', models.PositiveIntegerField(default=1960, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2020)])),
                ('school', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
