# Generated by Django 2.2.5 on 2020-10-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0023_experience_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/portfolio/images'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/portfolio/images'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/portfolio/images'),
        ),
    ]
