# Generated by Django 2.2.5 on 2020-10-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0026_biodata_achieves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='achieves',
            new_name='achives',
        ),
    ]
