# Generated by Django 2.2.5 on 2020-10-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0027_auto_20201024_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='achives',
            field=models.ManyToManyField(related_name='archives', to='blog.Post'),
        ),
    ]
