# Generated by Django 2.2.5 on 2020-10-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0028_auto_20201024_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='achives',
            new_name='archives',
        ),
    ]
